### PR TITLE
Add ability to configure lower case words

### LINKED ISSUE #8: Ability to configure lower case words
Thank you for your plugin!

It would be cool to be able to customize words to be lower case. Something like this:

```jsonc
// .remarkrc
{
  "plugins": {
    "remark-lint-heading-capitalization": ["error", {
      "lowerCaseWords": ["и", "но", "в", "к", "до", "по"]
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by azat-io**
Closes #8

### CODE REVIEW

**Comment by azat-io** [comment]
@ilyatitovich Hey. What do you think about it?

**Comment by ilyatitovich** [comment]
Hi Azat! Thanks for your help, nice implementation. I'm really appreciate. I'm going to work on plugins updates later, because I'm doing other things now. I'm looking for a job, maybe any open role in your current company?

**Comment by azat-io** [comment]
I'm sorry, but at this time, there is no

**Comment by nahoc** [comment]
can you please merge this PR?

**Comment by ilyatitovich** [comment]
Thanks!

**Pull request merged**
